# Generated by Django 5.1.1 on 2024-09-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_alter_movie_duration_alter_movie_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name'], 'verbose_name_plural': 'Директоры'},
        ),
    ]
